import Head from "next/head";
import Grid from "../components/Home/Grid";
import Jumbotron from "../components/Home/Jumbotron";
import Picbg from "../components/Home/picbg";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Picbg />
        <Jumbotron />
        <Grid />
      </main>
    </>
  );
}
